# useful for testing with `VOLUME_ID=vol-xxxx docker-compose build && VOLUME_ID=vol-xxxx docker-compose run attacher`
# your docker command should be set up against ec2 machine
attacher:
  build: ./
  environment:
    VOLUME_ID: "${VOLUME_ID}"
  volumes:
    - /:/host_root
  privileged: true
